### ISSUE TITLE
Library won't build, giving error "'init(pemRepresentation:)' is only available in iOS 14.0 or newer"

### ISSUE THREAD

**Issue by morpholio** [apple/app-store-server-library-swift#10]
Adding the library to a new Swift or SwiftUI project in Xcode 15 and building yields this error:

'init(pemRepresentation:)' is only available in iOS 14.0 or newer

The deployment target for the sample app is iOS 17 (changing it has no effect). Using Xcode 15.0 (15A240d).

**Comment by alexanderjordanbaker** [comment]
Hello @morpholio. Are you attempting to use this library inside an app within XCode? Or run this as part of a server written in Swift

**Comment by alexanderjordanbaker** [comment]
What feature are you attempting to use within the app? This library is only designed to work for Swift on Server, the StoreKit framework on device generally does everything this library would do that is doable on a device, but if you describe more about your use-case I can investigate further
