### ISSUE TITLE
Hope to add support to the new fields of JWSTransactionDecodedPayload added in App Store Server API 1.10

### ISSUE THREAD

**Issue by SeaHub** [apple/app-store-server-library-swift#11]
First of all, thanks to great package which saves me a lot of time!

## Background
In 10/2023, Apple release App Store Server API 1.10 version, which adds following fields in JWSTransactionDecodedPayload
- currency: The three-letter ISO 4217 currency code associated with the price parameter. This value is present only if price is present.
- offerDiscountType: The payment mode you configure for the subscription offer, such as Free Trial, Pay As You Go, or Pay Up Front.
- price: An integer value that represents the price multiplied by 1000 of the in-app purchase or subscription offer you configured in App Store Connect and that the system records at the time of the purchase. For more information, see [price](https://developer.apple.com/documentation/appstoreservernotifications/price?changes=latest_minor). The currency parameter indicates the currency of this price.

As for me, currency and price is so important that we cannot figure out how much user actually paid without them.
Besides, offerDiscountType is also important for we to track user subscription activity.

## Hopes
I wish that we can support the fields above published in App Store Server API 1.10 as soon as possible
If we need to support above features, the [JWSTransactionDecodedPayload](https://github.com/apple/app-store-server-library-swift/blob/main/Sources/AppStoreServerLibrary/Models/JWSTransactionDecodedPayload.swift) model in our code may be needed to update to the lastest as the apple documentation  [Apple JWSTransactionDecodedPayload](https://developer.apple.com/documentation/appstoreserverapi/jwstransactiondecodedpayload) shows

**Comment by alexanderjordanbaker** [comment]
Resolved in #12
