### ISSUE TITLE
The library isn't compatible with newer swift versions 

### ISSUE THREAD

**Issue by orre1996** [apple/app-store-server-library-swift#36]
Seems like some packages needs to be updated

<img width="1085" alt="Skärmavbild 2024-03-13 kl  14 07 44" src="https://github.com/apple/app-store-server-library-swift/assets/38316091/306040c6-cea9-4275-b697-335106b19830">

**Comment by alexanderjordanbaker** [comment]
This library only supports Swift on Server, not devices like an iPhone. We recommend using StoreKit 2 on device.

**Comment by orre1996** [comment]
Ohhh that makes sense, sorry about that.
Unfortunately promotional offers can't be done with only StoreKit 2, you need to create the signature on the server I guess

**Comment by alexanderjordanbaker** [comment]
So yes, to create a promotional offer you need a server which has access to your app's private signing key (Another reason this can't be done on device, as the app wouldn't have access to this key). We can track that issue on the issue you created on the node library.
