### ISSUE TITLE
I am getting response?.revision  nil always when fetching transaction detail using transaction id

### ISSUE THREAD

**Issue by awaiscs77** [apple/app-store-server-library-swift#47]
I am getting response?.revision as nil always when fetching transaction details using the transaction ID. However, I am receiving a signed response, but I was expecting the parsed JSON of the transaction record.

**Comment by alexanderjordanbaker** [comment]
Hello @awaiscs77, please see the documentation for the appropriate endpoint, I believe you are talking about the Get Transaction History endpoint? In https://developer.apple.com/documentation/appstoreserverapi/historyresponse, the signedTransaction array is an array of signed transactions that can be decoded with a SignedDataVerifier. As to revision being nil, are you saying you received a response with a non-empty signedTransactions array but with a nil revision?

**Comment by alexanderjordanbaker** [comment]
Please open another issue if you continue to have issues
