### ISSUE TITLE
Add deviceVerification / deviceVerificationNonce to decoded Transactions

### ISSUE THREAD

**Issue by klanchman** [apple/app-store-server-library-swift#55]
Transaction JWSs originating from a device contain `deviceVerification` and `deviceVerificationNonce` properties, but the App Store Server Library does not decode them. The library only has these fields on AppTransaction.

It'd be good if the library could expose these fields 😄

**Comment by alexanderjordanbaker** [comment]
@klanchman Thanks for reaching out. We can look at adding those, but I'm curious, server-side, what use cases do you see for those fields?

**Comment by klanchman** [comment]
@alexanderjordanbaker I'm glad you asked, because reading your question made me immediately realize my use case for `deviceVerification` won't actually solve what I was aiming to solve 🙃 

What I was thinking about using this for is confirming that a Transaction JWS sent to my server "belongs" to the client that made the request. (For example, avoiding someone sniffing my app's network traffic, grabbing their JWS, and sharing it with others / using it to make server requests outside of my app.) But checking `deviceVerification` on the server won't help, because the client would also need to send its `deviceVerificationID`, which in this example could be grabbed alongside the JWS and shared just as before.[^1]

Anyway, since this isn't something I'd use after all, I'm fine if this issue is closed 👍 

[^1]: This isn't really a major threat for my app/server. If I really needed this solved I think App Attest would be the way to go. But I figured if I could solve it just through simple-ish StoreKit means that it'd be worth doing.
