### ISSUE TITLE
Security of the ReceiptUtility.extractTransactionId(appReceipt:) function for App Store Receipt

### ISSUE THREAD

**Issue by shimastripe** [apple/app-store-server-library-swift#66]
I have confirmed that it is recommended to use the `ReceiptUtility.extractTransactionId(appReceipt:)` function of this library to extract the transaction_id from the App Store Receipt on my backend server, and then use the extracted transaction_id to retrieve data via the App Store Server API, as part of a backward-compatible migration process.

My understanding is that the App Store Server Library extracts the transaction_id from the receipt without performing tamper verification. This is noted in the comments.

https://github.com/apple/app-store-server-library-swift/blob/b631d3727875dbd2f3d1d3733c514360bf01de36/Sources/AppStoreServerLibrary/ReceiptUtility.swift#L13

Is this approach based on the assumption that valid transaction_ids have not been leaked externally?
I am concerned about the possibility that a user who knows a valid transaction_id might be able to tamper with the contents of the receipt.

Thanks.

**Comment by alexanderjordanbaker** [comment]
@shimastripe 

Original StoreKit, where these receipts come from, is deprecated. If you can move to StoreKit 2, which has JWS-style signed data, this is the best possible solution. If that isn't possible, the App Store Server API does show you that the transaction id is legitimate, but if you want to verify the receipt itself, you can following the steps as described in  https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device to validate the receipt on your server.

**Comment by shimastripe** [comment]
@alexanderjordanbaker Thank you for your advice!

Yes, many are shifting towards the signed transaction mechanism, and this endpoint adjustment is for backward compatibility.

We were considering replacing the parts where we received receipts from the device and performed verifyReceipt() with this method, but after watching the WWDC24 videos, I decided that receipt verification itself would no longer be necessary. 

Therefore, I wanted to ask if there is any risk in limiting the verification of receipts sent from the device to just checking for a valid transaction_id. 
(For example, whether this was intended to be limited to ServerNotification receipts only, etc.)

**Comment by alexanderjordanbaker** [comment]
@shimastripe Unfortunately, all I can really say is what is above.
